// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EvalScript(arg1) {
  return window['go']['mrat']['Server']['EvalScript'](arg1);
}

export function SetGain(arg1) {
  return window['go']['mrat']['Server']['SetGain'](arg1);
}

export function Start(arg1) {
  return window['go']['mrat']['Server']['Start'](arg1);
}
