// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * Knob is a ugen representing a control that can be turned to
 * adjust a value.
 */
export class Knob {
    /**
     * Creates a new Knob instance.
     * @param {Partial<Knob>} [$$source = {}] - The source object to create the Knob.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("min" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["min"] = 0;
        }
        if (!("max" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max"] = 0;
        }
        if (!("def" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["def"] = 0;
        }
        if (!("step" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["step"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Knob instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Knob}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Knob(/** @type {Partial<Knob>} */($$parsedSource));
    }
}
