// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class OpenFileDialogResponse {
    /**
     * Creates a new OpenFileDialogResponse instance.
     * @param {Partial<OpenFileDialogResponse>} [$$source = {}] - The source object to create the OpenFileDialogResponse.
     */
    constructor($$source = {}) {
        if (!("FileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FileName"] = "";
        }
        if (!("Content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFileDialogResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenFileDialogResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFileDialogResponse(/** @type {Partial<OpenFileDialogResponse>} */($$parsedSource));
    }
}
