// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetNotes():Promise<Array<string>>;

export function RegisterWaveformCallback(arg1:main.WaveformCallback):Promise<void>;

export function SetGain(arg1:number):Promise<void>;
