// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSampleRate():Promise<number>;

export function OpenFileDialog():Promise<main.OpenFileDialogResponse>;

export function PlayFile(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;
