// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function RegisterWaveformCallback(arg1) {
  return window['go']['main']['App']['RegisterWaveformCallback'](arg1);
}

export function SetChord(arg1, arg2) {
  return window['go']['main']['App']['SetChord'](arg1, arg2);
}

export function SetGain(arg1) {
  return window['go']['main']['App']['SetGain'](arg1);
}
