// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ugen} from '../models';
import {mrat} from '../models';
import {main} from '../models';

export function GetKnobs():Promise<Array<ugen.Knob>>;

export function GetNSPublics():Promise<Array<mrat.Symbol>>;

export function GetSampleRate():Promise<number>;

export function OpenFileDialog():Promise<main.OpenFileDialogResponse>;

export function PlayFile(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function Silence():Promise<void>;
