// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GraphDot() {
  return window['go']['main']['App']['GraphDot']();
}

export function RegisterWaveformCallback(arg1) {
  return window['go']['main']['App']['RegisterWaveformCallback'](arg1);
}

export function SetGain(arg1) {
  return window['go']['main']['App']['SetGain'](arg1);
}

export function SetShowSpectrum(arg1) {
  return window['go']['main']['App']['SetShowSpectrum'](arg1);
}

export function SetShowSpectrumHist(arg1) {
  return window['go']['main']['App']['SetShowSpectrumHist'](arg1);
}
