name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

  pull_request:
    branches: [main]

  workflow_dispatch: {}

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          # - name: 'App'
          #   platform:  'linux/amd64'
          #   os: 'ubuntu-latest'
          # - name: 'App'
          #   platform:  'windows/amd64'
          #   os: 'windows-latest'
          - name: 'App'
            platform:  'darwin/arm64'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --run 'PATH=$(go env GOPATH)/bin:$PATH make app'
